# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1c01bfb9fcfc23b1df507c4a5efadef01939f145b96966d614e3d7bb2aa9bf24568d881b540206740507473ae86026c3399bcd5295e5c22c1cf0c377978610a

test:
  secret_key_base: bbbb605b050f88760d504f336a0ebff3d72048792333fd60bc824c9f04c42255cc0ea8152db2fd1531dcc5578ce7974d6f97a40faf03c125e0924430335f642a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
